### ISSUE TITLE
If `ncuts` is 0, throws error instead of gracefully warning and exiting

### ISSUE THREAD

**Issue by jpsmith5** [Boyle-Lab/F-Seq2#1]
https://github.com/Boyle-Lab/F-Seq2/blob/2eba80fcc32a156b6deff3104251f32d2905dbe5/fseq2/fseq2.py#L182

Came across this when testing on some very small example files. If the source file actually yields no cuts, then calculating the `cut_density` in `calculate threshold` throws an error. It would be perhaps more helpful for the tool to recognize when an input file contains no cuts and warn the user and exit with a message.

**Comment by nsamzhao** [comment]
Thanks for the suggestion. It has been fixed in version 2.0.3
