### ISSUE TITLE
peaks.narrowPeak and summits.narrowPeak is not loaded to UCSC as custom track error

### ISSUE THREAD

**Issue by demis001** [Boyle-Lab/F-Seq2#3]
@aboyle @nsamzhao 

I got this error while loading to UCSC browser as custom track which seems there:
```
Error File 'GM12376-DEB-1000_peaks.narrowPeak.chr' - Error line 1 of custom track: thickStart after thickEnd
```

I have generated a narrow peaks from ATAC-seq data using the following command:

```
fseq2 callpeak ${bemin}/${filename}.prichr.sorted.rmDup.namesorted.bam \
         -f 0 -l 600 -t 4.0 -pe -cpus ${PPN} -nfr_upper_limit 150 -pe_fragment_size_range auto -p_thr 0.05  -standard_narrowpeak -sort_by pValue -o  fseqpeaks_21068Rsy/${filename} \
         -name ${filename}
```
The data is from paired-end ATAC-Seq. I got two files: 

GM12376-DEB-100_peaks.narrowPeak  
GM12376-DEB-100_summits.narrowPeak

On your github note, you suggested the summits file is to visualize in genome viewer such as UCSC. I see both has written in strand specific manner but without no strand information. 

The summit file is one base long based on start and end (which may show the center summit of the peak region). The only thing I have added to the fseq2 output was to add `chr` at the start of the line (I used Ensembl as ref genome). 

chr3	93470630	93470631	GM12376-DEB-1000_summit_0	2829	.	395.179	282.943	277.703	0
chr16	1782831	1782832	GM12376-DEB-1000_summit_1	1746	.	296.913	174.654	169.714	0
chr4	781944	781945	GM12376-DEB-1000_summit_2	1689	.	296.229	168.904	164.14	0
chr17	82023063	82023064	GM12376-DEB-1000_summit_3	1677	.	328.671	167.777	163.138	0
chr19	42268966	42268967	GM12376-DEB-1000_summit_4	1598	.	319.611	159.812	155.27	0
chr19	14117960	14117961	GM12376-DEB-1000_summit_5	1542	.	249.44	154.239	149.776	0
chr19	5904543	5904544	GM12376-DEB-1000_summit_6	1526	.	316.756	152.681	148.294	0
chr8	25458597	25458598	GM12376-DEB-1000_summit_7	1526	.	269.523	152.632	148.294	0
chr9	129080973	129080974	GM12376-DEB-1000_summit_8	1509	.	245.81	150.961	146.675	0
chr7	100586399	100586400	GM12376-DEB-1000_summit_9	1447	.	285.673	144.729	140.488	0

Any idea?

@demis001

**Comment by nsamzhao** [comment]
Hi @demis001 
Put a custom header would solve the issue. (e.g. track type=narrowPeak name="My narrowPeak"). See here for an explanation: https://groups.google.com/a/soe.ucsc.edu/g/genome/c/JzQtbjGbTnc?pli=1
Sam
