### ISSUE TITLE
"No reads contained in input file(s)."

### ISSUE THREAD

**Issue by kevinmuret** [Boyle-Lab/F-Seq2#6]
Hi,

I'm working with fseq2 with murine data. 
When I run fseq2, it works on a part of my .bed file (MT, X, Y, ....) and leaves out the "numerical" chromosomes (1 --> 18).
When I sub-select chromosomes 1 to 18, this is what it shows me:

_PROGRAM: fseq2.0.3 callpeak
F-Seq Version 2.0.3
\#1: Read in files and calculate parameters
/env/products/f-seq2/2.0.3/lib/python3.8/site-packages/fseq2/fseq2.py:57: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  bed['end_new'] = (bed[['end', 'strand']]).max(axis=1)
**Error: No reads contained in input file(s).**_

Note that my file contains 12868084 lines and its format (bed) seems classic: 
18      90600554        90600572        N1:1:HCGMLBGX5:3:23603:4197:5544/2      34      +
18      90600563        90600620        N1:1:HCGMLBGX5:2:13301:23722:11856/2    32      +
18      90600609        90600642        N1:1:HCGMLBGX5:3:23603:4197:5544/1      34      -
18      90600693        90600728        N1:1:HCGMLBGX5:2:13301:23722:11856/1    32      -
...

Do you have any idea what's going on?

Thanks !

**Comment by kevinmuret** [comment]
Update : if I change numerical chromosomes : 1 -> chr1 : it works !

**Comment by nsamzhao** [comment]
Yes, chromosomes should come with "chr". We will make this error more explicit! Thanks, Kevin.
